[versions]
agp = "8.13.0"
androidxJunit = "1.1.5"
appcompatVersion = "1.6.1"
constraintlayoutVersion = "2.1.4"
espressoCoreVersion = "3.5.1"
glide = "4.16.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
lifecycleCommonJava8 = "2.7.0"
lifecycleViewmodel = "2.6.2"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
materialVersion = "1.11.0"
recyclerview = "1.4.0"
roomRuntime = "2.6.1"

[libraries]
appcompat-v161 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
constraintlayout-v214 = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayoutVersion" }
espresso-core-v351 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
junit-v115 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycleCommonJava8" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata", version.ref = "lifecycleViewmodel" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycleViewmodel" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material-v1110 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

